name: CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Installing enviroment
        run: sudo apt update && sudo apt install libsdl2-dev libsdl2-dev libgl1-mesa-dev libglew-dev libsdl2-image-dev libglm-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build

      - name: Build
        run: cmake --build ${{github.workspace}}/build
